### ISSUE TITLE
problems parsing a string with query arguments

### ISSUE THREAD

**Issue by stianSjoli** [scala/scala-xml#101]
Hey, I am doing this in my code: println((XML.loadFile(file2) \ "cat:entries").length)
and in my file2 I have the xml: 
    cat:entries
"<"cat:entry URI="http://www.nitrc.org/ir/data/experiments/NITRC_IR_E10452/scans/T2/resources/bval/files?format=zip&projectIncludedInPath=true&subjectIncludedInPath=true" format="ZIP"/>  /cat:entries

This produces this error:
Exception in thread "main" org.xml.sax.SAXParseException; lineNumber: 8; columnNumber: 136; The reference to entity "projectIncludedInPath" must end with the ';' delimiter.
    at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
    at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
    at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
    at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
    at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1437)
    at com.sun.org.apache.xerces.internal.impl.XMLScanner.scanAttributeValue(XMLScanner.java:891)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanAttribute(XMLDocumentFragmentScannerImpl.java:1548)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1320)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2787)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
    at scala.xml.factory.XMLLoader$class.loadXML(XMLLoader.scala:41)
    at scala.xml.XML$.loadXML(XML.scala:60)
    at scala.xml.factory.XMLLoader$class.loadFile(XMLLoader.scala:48)
    at scala.xml.XML$.loadFile(XML.scala:60)
    at Curator$.delayedEndpoint$Curator$1(Curator.scala:19)
    at Curator$delayedInit$body.apply(Curator.scala:11)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
    at scala.App$class.main(App.scala:76)
    at Curator$.main(Curator.scala:11)
    at Curator.main(Curator.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

**Comment by stianSjoli** [comment]
I had to add "<" to make the xml visible.

**Comment by ashawley** [comment]
Sure, your XML file is not valid XML.  The ampersands (`&`) in the `URI` attribute should be quoted as `&amp;` entities:
<foo:bar ATTR="&">
```
<cat:entry URI="http://www.nitrc.org/ir/data/experiments/NITRC_IR_E10452/scans/T2/resources/bval/
files?format=zip&amp;projectIncludedInPath=true&amp;subjectIncludedInPath=true" format="ZIP"/>
```

Here's another example to show the difference:

```
scala> scala.xml.XML.loadString("""<foo:bar ATTR="&"/>""")
org.xml.sax.SAXParseException: The entity name must immediately follow the '&' in the entity reference.

scala> scala.xml.XML.loadString("""<foo:bar ATTR="&amp;"/>""")
res1: scala.xml.Elem = <foo:bar ATTR="&amp;"/>
```

Hope that helps,
Aaron

**Comment by stianSjoli** [comment]
Aron. It does. I confirmed it myself with an xml-validator, and wrote an email to the curators of the database that also confirmed the problem. I feel bad for not writing something about it here, but things have been a bit fast passed lately.

**Comment by ashawley** [comment]
After a year, I hope you were able to resolve your issue.

Best,
Aaron
