### ISSUE TITLE
Travis build failure

### ISSUE THREAD

**Issue by ashawley** [scala/scala-xml#224]
Scala 2.11.12, scala-js 0.6.23 and JDK8

https://travis-ci.org/scala/scala-xml/builds/383257994

This build is spurious, but the backtrace is new:

```
java.lang.NullPointerException
	at org.scalajs.jsenv.nodejs.AbstractNodeJSEnv$NodeComJSRunner$class.send(AbstractNodeJSEnv.scala:247)
	at org.scalajs.jsenv.nodejs.NodeJSEnv$ComNodeRunner.send(NodeJSEnv.scala:70)
	at org.scalajs.testadapter.ComJSEnvRPC.send(ComJSEnvRPC.scala:67)
	at org.scalajs.testcommon.RPCCore.call(RPCCore.scala:137)
	at org.scalajs.testadapter.TestAdapter.loadFrameworks(TestAdapter.scala:53)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$79.apply(ScalaJSPluginInternal.scala:1012)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$79.apply(ScalaJSPluginInternal.scala:986)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tpolecat** [comment]
I just ran into this as well, on another project. So you weren't hallucinating.

**Comment by ashawley** [comment]
Haven't seen this Travis build error in a while.  Presumably, it helhped to update Scalajs to 0.6.25.
