### ISSUE TITLE
OutOfMemoryError in MarkupParser caused by invalid markup declaration open

### ISSUE THREAD

**Issue by aldiyen** [scala/scala-xml#307]
Putting `<!` in a string to be parsed as XML or XHTML, without following it with some appropriate declaration such as `--` or whatever, causes an apparent infinite loop which eventually results in an OutOfMemoryError.

Example code:
```
import scala.io.Source
import scala.xml.parsing.XhtmlParser
val text = "<body>test <! </body>"
XhtmlParser(Source.fromString(text))
```

**Comment by ashawley** [comment]
What version of scala-xml are you using?  I couldn't reproduce your example with 1.2.0, see #333.

**Comment by aldiyen** [comment]
Sorry, I should've included a stack trace. In Scala 2.12.5, which appears to be bundled with scala-xml 1.0.6, I cannot reproduce the OOM error, and instead get `scala.xml.parsing.FatalError: broken comment`. In Scala 2.11.12 using scala-xml 1.2.0 I am able to reproduce the behavior.

Here's the stack trace from the 2.11.12 version:
```
scala> import scala.io.Source
import scala.io.Source

scala> import scala.xml.parsing.XhtmlParser
import scala.xml.parsing.XhtmlParser

scala> val text = "<body>test <! </body>"
text: String = <body>test <! </body>

scala> XhtmlParser(Source.fromString(text))
:1:14: '-' expected instead of ' '</body>             ^
:1:14: '-' expected instead of ' '             ^
java.lang.OutOfMemoryError: Java heap space
  at java.util.Arrays.copyOf(Arrays.java:3332)
  at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
  at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:649)
  at java.lang.StringBuilder.append(StringBuilder.java:202)
  at scala.collection.mutable.StringBuilder.append(StringBuilder.scala:267)
  at scala.xml.parsing.MarkupParser$class.xComment(MarkupParser.scala:398)
  at scala.xml.parsing.XhtmlParser.xComment(XhtmlParser.scala:21)
  at scala.xml.parsing.MarkupParser$class.content1(MarkupParser.scala:428)
  at scala.xml.parsing.XhtmlParser.content1(XhtmlParser.scala:21)
  at scala.xml.parsing.MarkupParser$class.content(MarkupParser.scala:459)
  at scala.xml.parsing.XhtmlParser.content(XhtmlParser.scala:21)
  at scala.xml.parsing.MarkupParser$class.element1(MarkupParser.scala:588)
  at scala.xml.parsing.XhtmlParser.element1(XhtmlParser.scala:21)
  at scala.xml.parsing.MarkupParser$class.content1(MarkupParser.scala:433)
  at scala.xml.parsing.XhtmlParser.content1(XhtmlParser.scala:21)
  at scala.xml.parsing.MarkupParser$class.document(MarkupParser.scala:247)
  at scala.xml.parsing.XhtmlParser.document(XhtmlParser.scala:21)
  at scala.xml.parsing.XhtmlParser$.apply(XhtmlParser.scala:32)
  ... 14 elided
```

**Comment by SethTisue** [comment]
@aldiyen I wonder if you are actually using the version of scala-xml you intended, as per https://github.com/scala/scala-xml/issues/195

**Comment by aldiyen** [comment]
Oh god that's horrifying. Hmm...

**Comment by aldiyen** [comment]
Okay I tested by overwriting the scala-xml JAR packaged with scala 2.11 and it didn't generate an OOM error so... that's exciting. Will close this, then. Thanks!
